### ISSUE TITLE
PR Potential

### ISSUE THREAD

**Issue by FrankC01** [mvines/solana-cli-template#3]
@mvines Wanted run the PR idea by you

1. Add a `program` source directory to the template that demonstrates exercising various program instructions, account state (data) management, etc.
2. Add a `keys` directory to support faux program  wallets and account keys
3. Add a `tests` directory with multiple test run scenarios (i.e. "no batteries required", etc.)

I realize there are lots of sample programs but my thoughts are that the intent of the template is to `kick start` others CLI implementations with boiler plate simplicity.

Thoughts? 

And, if you agree its a worthy addition, are we doing Draft PR's with incremental updates for review before finalizing? Or...?

**Comment by mvines** [comment]
The idea sounds great in general.  This seems it might look like a merge between this template and https://github.com/mvines/solana-bpf-program-template.

Instead of merging into here, perhaps the resulting template could just live in the main solana org instead of off in my personal area, alongside https://github.com/solana-labs/example-helloworld for example

**Comment by FrankC01** [comment]
Either here or there, up to you. If the latter, would you seed the new repo with your template first or is there a better approach?

**Comment by mvines** [comment]
If you build it in your area, we could either clone it in or the Solana org or just reference it from your area too.  It doesn’t need to land in here first.

**Comment by FrankC01** [comment]
OK, I'll break it into a new repo. Would still like your review as A) New to rust (4 months) and B) same for Solana although submitting a PR has hardened that up a bit...

**Comment by FrankC01** [comment]
Hi, I've just changed [solana-cli-program-template](https://github.com/hashblock/solana-cli-program-template) to be a template. Integrated testing includes loading the sample program and I've extended `main` arguments to include commands to drive the program.

I know you are busy, but what would you recommend as "next steps" ?
